### PR TITLE
Migrate or archive older files

### PR DESCRIPTION
**Pull request by kathycarothers**
Migrate or archive older files from old /open transition directory #5112

### CODE REVIEW

**Review by dorothyyeager — COMMENTED** [review]
Add redirect for rewrite ^/open/documents/Non-Federal-Source-Travel-Report-April1-Sept30-2016.pdf https://www.fec.gov/about/open/ redirect;

(Sorry I forgot to copy over that line before.)

**Review by kathycarothers — COMMENTED** [review]
I have added the missing redirect now.

**Review by dorothyyeager — APPROVED** [review]
Looks good to me! Thanks Kathy!

**Review by patphongs — APPROVED** [review]
Looks good @kathycarothers 👍

**Pull request merged**
