### PR TITLE
Adds redirects for tickets in 13.5

### PR DESCRIPTION
**Pull request by djgarr**
Redirects Enforcement statistics and things Dorothy found in inventory.

See https://github.com/fecgov/fec-cms/issues/4073

### CODE REVIEW

**Comment by dorothyyeager** [comment]
@patphongs There's a redirect in transition and in Wagtail for /pages/brochures/TestingtheWaters.shtml that is not working and I can't figure out why not? We looked at the code when putting in this PR but it looked correct to us.
/pages/brochures/TestingtheWaters.shtml should redirect to https://www.fec.gov/help-candidates-and-committees/registering-candidate/testing-the-waters-possible-candidacy/

**Review by patphongs — APPROVED** [review]
Looks good, thanks!

**Comment by patphongs** [comment]
> @patphongs There's a redirect in transition and in Wagtail for /pages/brochures/TestingtheWaters.shtml that is not working and I can't figure out why not? We looked at the code when putting in this PR but it looked correct to us.
> /pages/brochures/TestingtheWaters.shtml should redirect to https://www.fec.gov/help-candidates-and-committees/registering-candidate/testing-the-waters-possible-candidacy/

@dorothyyeager I checked this redirect in transition and Wagtail and they both redirect as expected

**Comment by dorothyyeager** [comment]
Thanks @patphongs - must be Chrome caching for me. Glad it is working!

**Pull request merged**
