### PR TITLE
Add a redirect for line 10

### PR DESCRIPTION
**Pull request by kathycarothers**
Add a new redirect for line 10 So this link for support would go to the data conversion tools link

### CODE REVIEW

**Review by patphongs — APPROVED** [review]
Thanks @kathycarothers !

**Review by dorothyyeager — CHANGES_REQUESTED** [review]
Looks good, but I caught something on line 11 right below the new entry. We should close the space between /support and /help-candidates-etc.

**Comment by dorothyyeager** [comment]
After discussing with @patphongs we'll leave this redirect on line 11 alone so as not to break anything. That means I'll approve and merge since the change @kathycarothers put in looks good to go.

**Review by dorothyyeager — APPROVED** [review]
Approved.

**Pull request merged**
