### PR TITLE
Create redirects-e-regs.conf

### PR DESCRIPTION
**Pull request by dorothyyeager**
These three pages for regs (11 CFR 111.24, 111.43 and 111.44):
https://www.fec.gov/regulations/111-24/2020-annual-111
https://www.fec.gov/regulations/111-43/2020-annual-111
https://www.fec.gov/regulations/111-44/2020-annual-111

~will need to redirect to their ecfr pages:
https://www.ecfr.gov/cgi-bin/text-idx?SID=6f2b90c7c55a428fa3aaa938d6cd54c1&mc=true&node=se11.1.111_124&rgn=div8
https://www.ecfr.gov/cgi-bin/text-idx?SID=6f2b90c7c55a428fa3aaa938d6cd54c1&mc=true&node=se11.1.111_143&rgn=div8
https://www.ecfr.gov/cgi-bin/text-idx?SID=6f2b90c7c55a428fa3aaa938d6cd54c1&mc=true&node=se11.1.111_144&rgn=div8~

Redirecting to shorter URLs after checking with @PaulClark2 

will need to redirect to their ecfr pages:
https://www.ecfr.gov/cgi-bin/text-idx?node=se11.1.111_124
https://www.ecfr.gov/cgi-bin/text-idx?node=se11.1.111_143
https://www.ecfr.gov/cgi-bin/text-idx?node=se11.1.111_144

### CODE REVIEW

**Comment by dorothyyeager** [comment]
This is ready for review; however OGC may want to include some sort of bubble note on the PDF so leaving in blocked until we're sure. @patphongs @AmyKort @lbeaufort

**Review by lbeaufort — APPROVED** [review]
Great work, @dorothyyeager! I tested a manual deploy with branch `lb-dorothyyeager-proxy273-deploy-2` and it looks great.

**Comment by dorothyyeager** [comment]
No longer blocked but now we are going to change out the links in the redirect to point to the ecfr ones in the related ticket.

**Comment by dorothyyeager** [comment]
Ready for your review @lbeaufort @patphongs

**Comment by lbeaufort** [comment]
@dorothyyeager I modified the eCFR links to remove seemingly unneeded parameters (updated the body of the PR too)

Dev testing links

https://dev.fec.gov/regulations/111-24/2020-annual-111
https://dev.fec.gov/regulations/111-43/2020-annual-111
https://dev.fec.gov/regulations/111-44/2020-annual-111

**Review by lbeaufort — APPROVED** [review]

**Pull request merged**
